Orn search
openstax/openstax-resource-names pull request #2
Opened 2022-11-28 22:00 UTC by TomWoodward

2022-11-29 22:18 UTC, Dantemss requested changes
Mostly looks good, just a few small things

2022-11-29 22:18 UTC, Dantemss commented on packages/orn-locator/src/index.ts
> +      result[key as keyof Patterns] = {items: innerResult as any, name: pattern.name};
Gnarly types I see but yeah I couldn't figure out how to fix them either...

2022-11-29 22:18 UTC, Dantemss commented on packages/orn-locator/src/resolvers/books.ts
> +const memoryTreeSearch = (getRank: (node: any) => number) => (node: any): Array<{node: any; rank: number}> => {
Isn't there a way to parametrize the node type here? Just to make sure they are all the same type.

2022-11-29 22:18 UTC, Dantemss commented on packages/orn-locator/src/resolvers/books.ts
> +  return rank > 0 ? [{node, rank}, ...contents] : contents;
`rank` is more like `score` here but it's very minor, no need to change it

2022-11-29 22:18 UTC, Dantemss commented on packages/orn-locator/src/resolvers/books.ts
> +      .slice(0, 5)
This limit of 5 feels like it should be configurable?

2022-11-29 22:18 UTC, Dantemss commented on packages/orn-locator/src/resolvers/books.ts
> +  const quotedTerms = [...query.matchAll(/"(.+)"/g)].map(match => match[1]);
This should probably be `[^"]+` instead of `.+` otherwise the match is garbled if there are multiple quotes.

2022-11-30 15:30 UTC, TomWoodward commented on packages/orn-locator/src/resolvers/books.ts
> +const memoryTreeSearch = (getRank: (node: any) => number) => (node: any): Array<{node: any; rank: number}> => {
yes, the internal types in this library are garbage, i'm trying not to spend too much time on it.

2022-11-30 16:33 UTC, Dantemss approved these changes

2022-11-30 16:50 UTC, merged